services:
  api:
    container_name: LibreChat
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.librechat.rule=Host(`${TRAEFIK_HOST}`)'
      - 'traefik.http.services.librechat.loadbalancer.server.port=3080'
    networks:
      - librechat_default
    env_file:
      - stack.env
    build:
      context: .
      target: node

  mongodb:
    build:
      context: .
      target: node
    image: mongo:4.4.18
    networks:
      - librechat_default
      
networks:
    librechat_default:
